export default {
  SHOW_ARTICLE: 'SHOW_ARTICLE',
  SHOW_ARTICLES: 'SHOW_ARTICLES',
  SHOW_COMMENTS: 'SHOW_COMMENTS',
  ADD_ARTICLE: 'ADD_ARTICLE',
  ADD_COMMENT: 'ADD_COMMENT',
  SET_FORM_TOKEN: 'SET_FORM_TOKEN'
}
