export default {
  SHOW_ARTICLE: 'SHOW_ARTICLE',
  SHOW_ARTICLES: 'SHOW_ARTICLES',
  SHOW_COMMENTS: 'SHOW_COMMENTS',
  ADD_ARTICLE: 'ADD_ARTICLE',
  ADD_COMMENT: 'ADD_COMMENT',
  ADD_CATEGORY: 'ADD_CATEGORY',
  SHOW_CATEGORIES: 'SHOW_CATEGORIES',
  TOGGLE_CATEGORY: 'TOGGLE_CATEGORY',
  RESET_SELECTED_CATEGORIES: 'RESET_SELECTED_CATEGORIES'
}
